### ISSUE TITLE
Installing interface add-on from URL and README.TXT file

### ISSUE THREAD

**Issue by genemars** [swaner/HomeGenieTelldusInterface#1]
Hi @swaner ,

just to let you know that in latest HG, interface add-on packages can be installed by entering its URL.
For your Telldus add-on the url should be:
https://github.com/swaner/HomeGenieTelldusInterface/raw/master/Tellstick_0_9.zip
Also if you include a _README.TXT_ file in the **zip** package, the text will be displayed to the user before installing the add-on, so it can be useful to include all install instructions/dependencies.

![hg_install_addons](https://cloud.githubusercontent.com/assets/6654265/7428697/4fc1bff4-eff5-11e4-9813-915a6b22b9f8.png)

Cheers,
g.

**Comment by swaner** [comment]
Great stuff, I added the readme.txt file to the zip. I had some issues installing from URL but didn't have time to investigate why. When using FileUpload everything worked great on the raspberry pi 2  :+1:

**Comment by genemars** [comment]
the download issue might be related to the HTTP SSL connection.
SSL in general will only work if latest mono is installed (>=4.0) and the package _ca-mono-certificates_ is also installed and updated.
